name: tracking_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  google_fonts: ^6.3.1
  injectable:
  get_it:
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  retrofit: ^4.7.2
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  dio_cache_interceptor: ^4.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:
  analyzer:
  hive_generator:
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  mockito: ^5.4.4


flutter:

  generate: true
  uses-material-design: true