name: Flutter Linting

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Analyzer
        run: flutter analyze --no-fatal-warnings
