name: Slack Notification After Any Workflow

on:
  workflow_run:
    types:
      - completed  # يشتغل بعد ما أي workflow يخلص

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Slack Status Emoji
        id: status
        run: |
          case "${{ github.event.workflow_run.conclusion }}" in
            success) echo "emoji=:white_check_mark:" >> $GITHUB_OUTPUT ;;
            failure) echo "emoji=:x:" >> $GITHUB_OUTPUT ;;
            cancelled) echo "emoji=:stop_sign:" >> $GITHUB_OUTPUT ;;
            *) echo "emoji=:grey_question:" >> $GITHUB_OUTPUT ;;
          esac

      - name: Send Slack Notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data '{
            "channel": "C09GFR4UP3N",
            "text": "${{ steps.status.outputs.emoji }} Workflow *${{ github.event.workflow_run.name }}* completed with status *${{ github.event.workflow_run.conclusion }}*\nBranch: *${{ github.event.workflow_run.head_branch }}*\nActor: *${{ github.event.workflow_run.actor.login }}*\n➡️ Check run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          }' \
          https://slack.com/api/chat.postMessage
