name: Slack Notifications for All Updates

on:
  push:
    branches:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - closed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Info
        id: info
        run: |
          SEPARATOR="──────────────────────────────"
          if [ "${{ github.event_name }}" == "push" ]; then
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            MESSAGE=":rocket: *Push on branch* \`${BRANCH_NAME}\` by *${{ github.actor }}*\n➡️ Commit: ${{ github.sha }}\n${SEPARATOR}"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_ACTION="${{ github.event.action }}"
            PR_NUMBER="${{ github.event.number }}"
            PR_BRANCH="${{ github.event.pull_request.head.ref }}"
            PR_ACTOR="${{ github.event.pull_request.user.login }}"
            MESSAGE=":twisted_rightwards_arrows: *Pull Request #${PR_NUMBER} ${PR_ACTION}* on branch \`${PR_BRANCH}\` by *${PR_ACTOR}*\n${SEPARATOR}"
          else
            MESSAGE="❓ Unknown event: \`${{ github.event_name }}\`\n${SEPARATOR}"
          fi
          echo "message=${MESSAGE}" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data "{
            \"channel\":\"C09GFR4UP3N\",
            \"text\":\"${{ steps.info.outputs.message }}\"
          }" \
          https://slack.com/api/chat.postMessage
