name: Notify Slack on Workflow Result

on:
  workflow_run:
    workflows: [
      "Firebase Distribution",
      "Flutter Linting",
      "Validate PR Title",
      "SonarQube Analysis",
      "Validate Branch Name",
      "Validate unit testing"
    ]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-message: |
            Workflow: ${{ github.event.workflow_run.name }}
            Branch: ${{ github.event.workflow_run.head_branch }}
            Actor: ${{ github.event.workflow_run.actor.login }}
            Status: ${{ github.event.workflow_run.conclusion }}
            Check run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
          channel-id: 'C09GFR4UP3N'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
