name: Slack Notifications for Workflows (Debug)

on:
  push:
    branches:
      - development

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data '{
            "channel":"C09GFR4UP3N",
            "text":"🚀 Push detected on branch *${{ github.ref_name }}* by *${{ github.actor }}* \n➡️ Commit: ${{ github.sha }}"
          }' \
          https://slack.com/api/chat.postMessage
