name: Notify Slack

on:
  workflow_run:
    workflows: ["*"] # يراقب كل الأعمال في المستودع
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: إرسال إشعار إلى Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: "${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.conclusion }}"
          SLACK_MESSAGE: "سير العمل `${{ github.event.workflow_run.name }}` على الفرع `${{ github.event.workflow_run.head_branch }}` انتهى بحالة: **${{ github.event.workflow_run.conclusion }}**. تحقق: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          SLACK_COLOR: ${{ github.event.workflow_run.conclusion == 'success' && '#00FF00' || github.event.workflow_run.conclusion == 'failure' && '#FF0000' || '#FFA500' }}