name: Slack Notifications for All Updates

on:
  push:
    branches:

  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - closed
  workflow_run:
    workflows:
      - "Firebase Distribution"
      - "Flutter Linting"
      - "Validate PR Title"
      - "SonarQube Analysis"
      - "Validate Branch Name"
      - "Validate unit testing"
    types:
      - completed

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Event Info
        id: info
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨"
            echo "message=🚀 Push on branch *${{ github.ref_name }}* by *${{ github.actor }}*\n➡️ Commit: ${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_ACTION="${{ github.event.action }}"
            PR_NUMBER="${{ github.event.number }}"
            PR_BRANCH="${{ github.event.pull_request.head.ref }}"
            PR_ACTOR="${{ github.event.pull_request.user.login }}"
           echo "message=🔀 Pull Request #${PR_NUMBER} ${PR_ACTION} on branch *${PR_BRANCH}* by *${PR_ACTOR}*" >> $GITHUB_OUTPUT
           echo "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨"
          else
            echo "message=❓ Unknown event: ${{ github.event_name }}" >> $GITHUB_OUTPUT
            echo "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨"
          
          fi

      - name: Send Slack Notification
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H "Content-type: application/json" \
          --data "{
            \"channel\":\"C09GFR4UP3N\",
            \"text\":\"${{ steps.info.outputs.message }}\"
          }" \
          https://slack.com/api/chat.postMessage
