name: Test slack

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: docker.pkg.github.com
      IMAGE_NAME: ${{ github.repository }}/alerta-cli
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Variables
        id: vars
        run: echo "SHORT_COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build \
            -t $IMAGE_NAME \
            -t $REPOSITORY_URL/$IMAGE_NAME:${{ env.SHORT_COMMIT_ID }} \
            -t $REPOSITORY_URL/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login $REPOSITORY_URL --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"

      - name: Publish Image
        run: docker push $REPOSITORY_URL/$IMAGE_NAME

      # Slack Notification (final status only)
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          channel: '#workflows'
        if: always()
